
package com.cloud.dbservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.2-06/22/2009 08:27 PM(mockbuild)-SNAPSHOT
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DataBaseService", targetNamespace = "http://data.cloud.com/")
public interface DataBaseService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityManager", targetNamespace = "http://data.cloud.com/", className = "com.cloud.dbservice.GetEntityManager")
    @ResponseWrapper(localName = "getEntityManagerResponse", targetNamespace = "http://data.cloud.com/", className = "com.cloud.dbservice.GetEntityManagerResponse")
    public String getEntityManager();

}
