
package com.cloud.dbservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.2-06/22/2009 08:27 PM(mockbuild)-SNAPSHOT
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "DataBaseServiceService", targetNamespace = "http://data.cloud.com/", wsdlLocation = "file:/C:/test/cloud/petstoreweb/src/DbServiceWS.wsdl")
public class DataBaseServiceService
    extends Service
{

    private final static URL DATABASESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cloud.dbservice.DataBaseServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cloud.dbservice.DataBaseServiceService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/test/cloud/petstoreweb/src/DbServiceWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/test/cloud/petstoreweb/src/DbServiceWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATABASESERVICESERVICE_WSDL_LOCATION = url;
    }

    public DataBaseServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataBaseServiceService() {
        super(DATABASESERVICESERVICE_WSDL_LOCATION, new QName("http://data.cloud.com/", "DataBaseServiceService"));
    }

    /**
     * 
     * @return
     *     returns DataBaseService
     */
    @WebEndpoint(name = "DataBaseServicePort")
    public DataBaseService getDataBaseServicePort() {
        return super.getPort(new QName("http://data.cloud.com/", "DataBaseServicePort"), DataBaseService.class);
    }

}
